openapi: '3.0.0'
info:
  version: 1.0.0
  title: タスクリストAPI

paths:
  /tasks:
    get:
      summary: タスク一覧取得
      description: タスク一覧のサマリーを取得します。ソートは作成日時の昇順です。
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TaskSummary'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/ServerError'
    post:
      summary: タスク作成
      description: 新しいタスクを作成します。
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTaskRequest'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          $ref: '#/components/responses/BadRequest'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/ServerError'

  /tasks/{id}:
    get:
      summary: タスク取得
      description: IDで指定されたタスクを取得します。
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/ResourceNotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/ServerError'

    put:
      summary: タスク更新
      description: タスクの詳細情報を更新します。リクエストボディには、少なくとも1つのプロパティが含まれている必要があります。
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTaskRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/ResourceNotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/ServerError'

    delete:
      summary: タスク削除
      description: タスクを削除します。
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: No Content
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/ResourceNotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/ServerError'

  /tasks/{id}/complete:
    patch:
      summary: タスク完了状態変更
      description: タスクの完了状態を変更します。
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CompleteTaskRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/ResourceNotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/ServerError'
components:
  schemas:
    TaskTitle:
      type: string
      description: タスクのタイトル
      minLength: 1
      maxLength: 100
      example: 'コーヒーを淹れる'
    TaskDescription:
      type: string
      description: タスクの説明
      maxLength: 1000
      example: '濃いめで'
    Task:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: タスクの一意の識別子(UUID)
          example: 'f0f8f5a0-309d-11ec-8d3d-0242ac130003'
        title:
          $ref: '#/components/schemas/TaskTitle'
        completed:
          type: boolean
          description: タスクが完了したかどうか
          example: false
        description:
          $ref: '#/components/schemas/TaskDescription'
        createdAt:
          type: string
          format: date-time
          description: タスクの作成日時（ISO 8601形式）
          example: '2021-06-22T14:24:02.071Z'
        updatedAt:
          type: string
          format: date-time
          description: タスクの最終更新日時（ISO 8601形式）
          example: '2021-06-22T14:24:02.071Z'
    TaskSummary:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: タスクの一意の識別子(UUID)
          example: 'f0f8f5a0-309d-11ec-8d3d-0242ac130003'
        title:
          $ref: '#/components/schemas/TaskTitle'
        completed:
          type: boolean
          description: タスクが完了したかどうか
          example: false
        createdAt:
          type: string
          format: date-time
          description: タスクの作成日時（ISO 8601形式）
          example: '2021-06-22T14:24:02.071Z'
        updatedAt:
          type: string
          format: date-time
          description: タスクの最終更新日時（ISO 8601形式）
          example: '2021-06-22T14:24:02.071Z'
    CreateTaskRequest:
      type: object
      required:
        - title
      properties:
        title:
          $ref: '#/components/schemas/TaskTitle'
        description:
          $ref: '#/components/schemas/TaskDescription'
    UpdateTaskRequest:
      type: object
      properties:
        title:
          $ref: '#/components/schemas/TaskTitle'
        description:
          $ref: '#/components/schemas/TaskDescription'
      example:
        title: ドーナッツを買う
        description: オールドファッションを2つ
    CompleteTaskRequest:
      type: object
      required:
        - completed
      properties:
        completed:
          type: boolean
          description: タスクが完了したかどうか
    ErrorResponse:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
  responses:
    BadRequest:
      description: BadRequest
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          examples:
            INVALID_REQUEST:
              $ref: '#/components/examples/INVALID_REQUEST'
    ResourceNotFound:
      description: ResourceNotFound
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          examples:
            TASK_NOT_AVAILABLE:
              $ref: '#/components/examples/TASK_NOT_AVAILABLE'
            RESOURCE_NOT_FOUND:
              $ref: '#/components/examples/RESOURCE_NOT_FOUND'
    TooManyRequests:
      description: TooManyRequests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          examples:
            SYSTEM_OVERLOAD:
              $ref: '#/components/examples/SYSTEM_OVERLOAD'
    ServerError:
      description: InternalServerError
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          examples:
            SYSTEM_ERROR:
              $ref: '#/components/examples/SYSTEM_ERROR'
            TASK_PROCESS_ERROR:
              $ref: '#/components/examples/TASK_PROCESS_ERROR'
            UNKNOWN_ERROR:
              $ref: '#/components/examples/UNKNOWN_ERROR'
  examples:
    INVALID_REQUEST:
      value:
        code: 'INVALID_REQUEST'
        message: 'The provided data is invalid.'
    TASK_NOT_AVAILABLE:
      value:
        code: 'TASK_NOT_AVAILABLE'
        message: 'The requested task could not be found.'
    RESOURCE_NOT_FOUND:
      value:
        code: 'RESOURCE_NOT_FOUND'
        message: 'The requested data could not be found.'
    SYSTEM_OVERLOAD:
      value:
        code: 'SYSTEM_OVERLOAD'
        message: 'The system is currently busy. Please try again later.'
    SYSTEM_ERROR:
      value:
        code: 'SYSTEM_ERROR'
        message: 'We encountered an internal error. Please try again.'
    TASK_PROCESS_ERROR:
      value:
        code: 'TASK_PROCESS_ERROR'
        message: 'Failed to process the task data.'
    UNKNOWN_ERROR:
      value:
        code: 'UNKNOWN_ERROR'
        message: 'An unexpected error occurred. Please try again.'
